#include "World/Modular/RARomanProceduralBuildingActor.h"
#include "Components/SceneComponent.h"
#include "UObject/ConstructorHelpers.h"
ARARomanProceduralBuildingActor::ARARomanProceduralBuildingActor(){PrimaryActorTick.bCanEverTick=false; SceneRoot=CreateDefaultSubobject<USceneComponent>(TEXT("RomanModularRoot")); RootComponent=SceneRoot;}
void ARARomanProceduralBuildingActor::BeginPlay(){Super::BeginPlay(); if(bGenerateOnBeginPlay){GenerateLayout(); RebuildInstances();}}
FRARomanGenerationResult ARARomanProceduralBuildingActor::GenerateLayout(){ ClearGeneratedLayout(); switch(BuildingParameters.BuildingType){case ERARomanBuildingType::Taberna: LastGenerationResult=URARomanBuildingRuleLibrary::BuildTabernaLayout(BuildingParameters); break; case ERARomanBuildingType::Temple: LastGenerationResult=URARomanBuildingRuleLibrary::BuildTempleLayout(BuildingParameters); break; case ERARomanBuildingType::StreetSection: LastGenerationResult=URARomanBuildingRuleLibrary::BuildStreetSectionLayout(BuildingParameters); break; default: LastGenerationResult=URARomanBuildingRuleLibrary::BuildSimpleHouseLayout(BuildingParameters); break;} return LastGenerationResult;}
bool ARARomanProceduralBuildingActor::ValidateConfiguration(TArray<FRARomanGenerationMessage>& W,TArray<FRARomanGenerationMessage>& E) const { URARomanConstructionValidator::ValidateParameters(BuildingParameters,W,E); if(ModuleCatalog.IsNull())W.Add({"NullCatalog",TEXT("Catalogo non impostato: saranno usati placement astratti o placeholder."),false}); return E.Num()==0; }
void ARARomanProceduralBuildingActor::RebuildInstances(){ for(auto* C:InstanceComponents){ if(C) C->DestroyComponent(); } InstanceComponents.Empty(); if(!bUseDebugPlaceholders)return; static ConstructorHelpers::FObjectFinder<UStaticMesh> Cube(TEXT("/Engine/BasicShapes/Cube.Cube")); if(!Cube.Succeeded())return; TMap<ERARomanModuleCategory,UInstancedStaticMeshComponent*> ByCat; for(const auto& P:LastGenerationResult.GeneratedPlacements){ UInstancedStaticMeshComponent*& C=ByCat.FindOrAdd(P.Category); if(!C){ C=NewObject<UInstancedStaticMeshComponent>(this); C->SetupAttachment(RootComponent); C->SetStaticMesh(Cube.Object); C->RegisterComponent(); InstanceComponents.Add(C);} C->AddInstance(P.Transform); }}
void ARARomanProceduralBuildingActor::ClearGeneratedLayout(){ for(auto* C:InstanceComponents){ if(C) C->DestroyComponent(); } InstanceComponents.Empty(); LastGenerationResult.GeneratedPlacements.Empty(); }
FString ARARomanProceduralBuildingActor::GetGenerationSummary() const {return FString::Printf(TEXT("Successo=%s, Moduli=%d, Warning=%d, Errori=%d"),LastGenerationResult.bSuccess?TEXT("true"):TEXT("false"),LastGenerationResult.GeneratedPlacements.Num(),LastGenerationResult.Warnings.Num(),LastGenerationResult.Errors.Num());}
